#include "./includes/ft_printf.h"
#include "locale.h"
#include <limits.h>
#include <signal.h>
#include <stdio.h>


int		main(void)
{


// 	ft_printf("%.4d\n", 42);
// 	printf("%.4d\n", 42);
//     ft_printf("%.4d\n", 424242);
// 	printf("%.4d\n", 424242);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%.4d\n", -424242);
// 	printf("%.4d\n", -424242);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%15.4d\n", 42);
// 	printf("%15.4d\n", 42);
// 	ft_printf("\n-----------------------------\n");
// 	ft_printf("%15.4d\n", 424242);
// 	printf("%15.4d\n", 424242);
// // 	ft_printf("\n-----------------------------\n");
//  	ft_printf("%8.4d\n", 424242424);
//  	printf("%8.4d\n", 424242424);
// ft_printf("\n-----------------------------\n");
//  	ft_printf("%15.4d\n", -42);
//  	printf("%15.4d\n", -42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%15.4d\n", -424242);
// 	printf("%15.4d\n", -424242);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%8.4d\n", -424242424);
// 	printf("%8.4d\n", -424242424);
// // 	ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.15d\n", 42);
// 	printf("%4.15d\n", 42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.15d\n", 424242);
// 	printf("%4.15d\n", 424242);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.8d\n", 424242424);
// 	printf("%4.8d\n", 424242424);
// // ft_printf("\n-----------------------------\n");
	ft_printf("%4.15d\n", -42);
	printf("%4.15d\n", -42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.15d\n", -424242);
// 	printf("%4.15d\n", -424242);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.8d\n", -424242424);
// 	printf("%4.8d\n", -424242424);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%.d, %.0d\n", 0, 0);
// 	printf("%.d, %.0d\n", 0, 0);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%.10d\n", -42);
// 	printf("%.10d\n", -42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%.4i\n", 42);
// 	printf("%.4i\n", 42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%15.4i\n", 42);
// 	printf("%15.4i\n", 42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.15i\n", 42);
// 	printf("%4.15i\n", 42);
// // ft_printf("\n-----------------------------\n");
// 	ft_printf("%.i, %.0i\n", 0, 0);
// 	printf("%.i, %.0i\n", 0, 0);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%.4u", 42);
// 	printf("%.4u\n", 42);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%.4u", 424242);
// 	printf("%.4u\n", 424242);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%15.4u", 42);
// 	printf("%15.4u\n", 42);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%15.4u", 424242);
// 	printf("%15.4u\n", 424242);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%8.4u", 424242424);
// 	printf("%8.4u\n", 424242424);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.15u", 42);
// 	printf("%4.15u\n", 42);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.15u", 424242);
// 	printf("%4.15u\n", 424242);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%4.8u", 424242424);
// 	printf("%4.8u\n", 424242424);
// ft_printf("\n-----------------------------\n");
// 	ft_printf("%.u, %.0u", 0, 0);
// 	printf("%.u, %.0u\n", 0, 0);
// ft_printf("\n-----------------------------\n");




	// ft_printf("\n-----------------------------\n");
	// ft_printf("len:%d", ft_printf("%lu", "-42"));
	// printf("len:%d", printf("%lu", "-42"));
	// ft_printf("\n-----------------------------\n");
		// ft_printf("{%30d}", 10000);
		// printf("\n-----------------------------\n");
		// ft_printf("{%10d}", -42);
		// printf("\n-----------------------------\n");
		// ft_printf("{%3c}", 0);
		// printf("\n-----------------------------\n");
		// ft_printf("{%5p}", 0);
		// printf("\n-----------------------------\n");
		// ft_printf("{%-15p}", 0);
		// printf("\n-----------------------------\n");
		// ft_printf("{%-13p}", &strlen);
		// ft_printf("{%-12p}", &strlen);
		// ft_printf("{%10R}");
		// ft_printf("{%30S}", L"我是一只猫。");
		// ft_printf("{%-30S}", L"我是一只猫。");
	//ft_printf("111%s333%s555", "222", "444");
	//ft_printf("111%s333%s555%saaa%sccc",
	//	"222", "444", "666", "bbb");
	//ft_printf("%s%s%s%s%s", "1", "2", "3", "4", "5");
	// ft_printf("%s%s%s%s%s");
	// ft_printf("%s", "abc");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("111%s333", "222");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%s333", "222");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("111%s", "222");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("{%s}", 0);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("{%s}", "");
	// ft_printf("\n-----------------------------\n");
	// printf("%s", "abc");
	// printf("\n-----------------------------\n");
	// printf("111%s333", "222");
	// printf("\n-----------------------------\n");
	// printf("%s333", "222");
	// printf("\n-----------------------------\n");
	// printf("111%s", "222");
	// printf("\n-----------------------------\n");
	// printf("{%s}", 0);
	// printf("\n-----------------------------\n");
	// printf("{%s}", "");
	// printf("\n-----------------------------\n");
	// ft_printf("This is a simple test.");
	// ft_printf("This is a simple test.\nSecond sentence.\n");
	// ft_printf("");
	// ft_printf("len:%d", ft_printf(""));
	// printf("len:%d", printf(""));
	//ft_printf("\n");
	//ft_printf("\n-----------------------------\n");
	// printf("This is a simple test.");
	// printf("This is a simple test.\nSecond sentence.\n");
	// printf("len0:%d", printf(""));
	// printf("\n");
	// ft_printf("%hhd%hhd", 1, 42);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhd", CHAR_MAX);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhd", CHAR_MAX + 42);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhd", CHAR_MIN);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhd", CHAR_MIN - 42);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhi%hhi", 0, 42);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhd", CHAR_MAX);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhd\n", CHAR_MAX + 42);
	// printf("%hhd\n", CHAR_MAX + 42);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhi", CHAR_MIN);
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%hhi", CHAR_MIN - 42);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhu, %hhu", 0, UCHAR_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hho, %hho", 0, UCHAR_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhx, %hhx", 0, UCHAR_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhX, %hhX", 0, UCHAR_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhu, %hhu", 0, UCHAR_MAX + 42);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hho, %hho", 0, UCHAR_MAX + 42);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhx, %hhx", 0, UCHAR_MAX + 42);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhX, %hhX", 0, UCHAR_MAX + 42);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhO, %hhO", 0, USHRT_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhU, %hhU", 0, USHRT_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhD, %hhD", 0, USHRT_MAX);
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhC, %hhC", 0, L'米');
	// ft_printf("\n-----------------------------\n");
	// // ft_printf("%hhS, %hhS", 0, L"米米");
	// ft_printf("\n-----------------------------\n");
		// ft_printf("%d", 42);
		// ft_printf("\n-----------------------------\n");
		// ft_printf("%d", -42);
		// ft_printf("\n-----------------------------\n");
		// ft_printf("before %d after", 42);
		// ft_printf("\n-----------------------------\n");
		// ft_printf("%d%d%d%d%d", 1, -2, 3, -4, 5);
		// ft_printf("\n-----------------------------\n");
		// ft_printf("a%db%dc%dd", 1, -2, 3);
		// ft_printf("\n-----------------------------\n");
		// ft_printf("%d", INT_MAX);
		// ft_printf("\n-----------------------------\n");
		// ft_printf("%d", INT_MIN);
		// ft_printf("Len:%d\n", ft_printf("%lu", -42));
		// printf("Len:%d", printf("%lu", -42));
		// ft_printf("{%04d}", 10000);
		// ft_printf("{%030d}", 10000);
		// ft_printf("{%030x}", 0xFFFF);
		// ft_printf("{%030X}", 0xFFFF);
		// ft_printf("{%03c}", 0);
		// ft_printf("{%05s}", "abc");
		// ft_printf("{%030S}", L"我是一只猫。");
		// ft_printf("{%05p}", 0);
		// ft_printf("{%05p}", &pointer_valueLargerThanMinWidth_zeroFlag);
	// ft_printf("111%s333%s555", "222", "444");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("111%s333%s555%saaa%sccc", "222", "444", "666", "bbb");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("%s%s%s%s%s", "1", "2", "3", "4", "5");
	//ft_printf("len:%d\n", ft_printf("%lu", -42));
	// ft_printf("This is a simple test.");
	// printf("This is a simple test.");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("This is a simple test.\nSecond sentence.\n");
	// printf("This is a simple test.\nSecond sentence.\n");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("");
	// printf("");
	// ft_printf("\n-----------------------------\n");
	// ft_printf("111%s333%s555%saaa%sccc",
	// 	"222", "444", "666", "bbb");
	// ft_printf("%s%s%s%s%s",
	// 	"1", "2", "3", "4", "5");
	//printf("\n");
//	printf("111%s333", "222");
	//printf("len:%d", printf("%lu", -42));
	/* setlocale(LC_ALL, "");
	ft_printf("FAKE = '%0.0d'\n", -42);
	printf("REAL = '%0.0d'\n", -42);
	ft_printf("FAKE = '%0d'\n", -42);
	printf("REAL = '%0d'\n", -42);
	ft_printf("FAKE = '%#d'\n", -42);
	printf("REAL = '%#d'\n", -42);
	ft_printf("FAKE = '%10d'\n", -42);
	printf("REAL = '%10d'\n", -42);
	ft_printf("FAKE = '%10.0d'\n", 0);
	printf("REAL = '%10.0d'\n", 0);
	ft_printf("FAKE = '%0d'\n", 0);
	printf("REAL = '%0d'\n", 0);
	ft_printf("FAKE = '%.0d'\n", 0);
	printf("REAL = '%.0d'\n", 0);
	ft_printf("FAKE = '%#.2d'\n", 0);
	printf("REAL = '%#.2d'\n", 0);
	ft_printf("FAKE = '%#20d'\n", 0);
	printf("REAL = '%#20d'\n", 0);
	ft_printf("FAKE = '%#-20d'\n", 55);
	printf("REAL = '%#-20d'\n", 55);
	ft_printf("FAKE = '%0d'\n", 55);
	printf("REAL = '%0d'\n", 55);
	ft_printf("FAKE = '%.0d'\n", 55);
	printf("REAL = '%.0d'\n", 55);
	ft_printf("FAKE = '%#.2d'\n", 55);
	printf("REAL = '%#.2d'\n", 55);
	ft_printf("FAKE = '%#20d'\n", 55);
	printf("REAL = '%#20d'\n", 55);
	ft_printf("FAKE = '%#-20d'\n", 55);
	printf("REAL = '%#-20d'\n", 55);
	ft_printf("FAKE = '%#-20d'd'\n", 55);
	printf("REAL = '%#-20d'd'\n", 55);
	ft_printf("FAKE = '%0.0d'\n", 0);
	printf("REAL = '%0.0d'\n", 0);
	ft_printf("FAKE = '%#.20d'\n", 0);
	printf("REAL = '%#.20d'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%lld'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lld'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lld'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lld'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lld'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lld'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lld'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lld'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%ld'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%ld'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%ld'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%ld'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.ld'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.ld'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.ld'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.ld'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%d'\n", INT_MAX);
	printf("REAL = INT_MAX      '%d'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%d'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%d'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.d'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.d'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.d'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.d'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hd'\n", 32767);
	printf("REAL = SHORT_MAX      '%hd'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hd'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hd'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hd'\n", -32768);
	printf("REAL = SHORT_MIN      '%hd'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hd'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hd'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhd'\n", 127);
	printf("REAL = CHAR_MAX      '%hhd'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhd'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhd'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhd'\n", -128);
	printf("REAL = CHAR_MIN      '%hhd'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhd'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhd'\n", -129);


	ft_printf("FAKE = '%0.0D'\n", -42);
	printf("REAL = '%0.0D'\n", -42);
	ft_printf("FAKE = '%0D'\n", -42);
	printf("REAL = '%0D'\n", -42);
	ft_printf("FAKE = '%#D'\n", -42);
	printf("REAL = '%#D'\n", -42);
	ft_printf("FAKE = '%10D'\n", -42);
	printf("REAL = '%10D'\n", -42);
	ft_printf("FAKE = '%10.0D'\n", 0);
	printf("REAL = '%10.0D'\n", 0);
	ft_printf("FAKE = '%0D'\n", 0);
	printf("REAL = '%0D'\n", 0);
	ft_printf("FAKE = '%.0D'\n", 0);
	printf("REAL = '%.0D'\n", 0);
	ft_printf("FAKE = '%#.2D'\n", 0);
	printf("REAL = '%#.2D'\n", 0);
	ft_printf("FAKE = '%#20D'\n", 0);
	printf("REAL = '%#20D'\n", 0);
	ft_printf("FAKE = '%#-20D'\n", 55);
	printf("REAL = '%#-20D'\n", 55);
	ft_printf("FAKE = '%0D'\n", 55);
	printf("REAL = '%0D'\n", 55);
	ft_printf("FAKE = '%.0D'\n", 55);
	printf("REAL = '%.0D'\n", 55);
	ft_printf("FAKE = '%#.2D'\n", 55);
	printf("REAL = '%#.2D'\n", 55);
	ft_printf("FAKE = '%#20D'\n", 55);
	printf("REAL = '%#20D'\n", 55);
	ft_printf("FAKE = '%#-20D'\n", 55);
	printf("REAL = '%#-20D'\n", 55);
	ft_printf("FAKE = '%#-20D'D'\n", 55);
	printf("REAL = '%#-20D'D'\n", 55);
	ft_printf("FAKE = '%0.0D'\n", 0);
	printf("REAL = '%0.0D'\n", 0);
	ft_printf("FAKE = '%#.20D'\n", 0);
	printf("REAL = '%#.20D'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llD'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llD'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llD'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llD'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llD'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llD'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llD'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llD'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lD'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lD'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lD'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lD'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lD'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lD'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lD'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lD'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%D'\n", INT_MAX);
	printf("REAL = INT_MAX      '%D'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%D'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%D'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.D'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.D'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.D'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.D'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hD'\n", 32767);
	printf("REAL = SHORT_MAX      '%hD'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hD'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hD'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hD'\n", -32768);
	printf("REAL = SHORT_MIN      '%hD'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hD'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hD'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhD'\n", 127);
	printf("REAL = CHAR_MAX      '%hhD'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhD'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhD'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhD'\n", -128);
	printf("REAL = CHAR_MIN      '%hhD'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhD'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhD'\n", -129);


	ft_printf("FAKE = '%0.0x'\n", -42);
	printf("REAL = '%0.0x'\n", -42);
	ft_printf("FAKE = '%0x'\n", -42);
	printf("REAL = '%0x'\n", -42);
	ft_printf("FAKE = '%#x'\n", -42);
	printf("REAL = '%#x'\n", -42);
	ft_printf("FAKE = '%10x'\n", -42);
	printf("REAL = '%10x'\n", -42);
	ft_printf("FAKE = '%10.0x'\n", 0);
	printf("REAL = '%10.0x'\n", 0);
	ft_printf("FAKE = '%0x'\n", 0);
	printf("REAL = '%0x'\n", 0);
	ft_printf("FAKE = '%.0x'\n", 0);
	printf("REAL = '%.0x'\n", 0);
	ft_printf("FAKE = '%#.2x'\n", 0);
	printf("REAL = '%#.2x'\n", 0);
	ft_printf("FAKE = '%#20x'\n", 0);
	printf("REAL = '%#20x'\n", 0);
	ft_printf("FAKE = '%#-20x'\n", 55);
	printf("REAL = '%#-20x'\n", 55);
	ft_printf("FAKE = '%0x'\n", 55);
	printf("REAL = '%0x'\n", 55);
	ft_printf("FAKE = '%.0x'\n", 55);
	printf("REAL = '%.0x'\n", 55);
	ft_printf("FAKE = '%#.2x'\n", 55);
	printf("REAL = '%#.2x'\n", 55);
	ft_printf("FAKE = '%#20x'\n", 55);
	printf("REAL = '%#20x'\n", 55);
	ft_printf("FAKE = '%#-20x'\n", 55);
	printf("REAL = '%#-20x'\n", 55);
	ft_printf("FAKE = '%#-20x'x'\n", 55);
	printf("REAL = '%#-20x'x'\n", 55);
	ft_printf("FAKE = '%0.0x'\n", 0);
	printf("REAL = '%0.0x'\n", 0);
	ft_printf("FAKE = '%#.20x'\n", 0);
	printf("REAL = '%#.20x'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llx'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llx'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llx'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llx'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llx'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llx'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llx'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llx'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lx'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lx'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lx'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lx'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lx'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lx'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lx'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lx'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%x'\n", INT_MAX);
	printf("REAL = INT_MAX      '%x'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%x'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%x'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.x'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.x'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.x'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.x'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hx'\n", 32767);
	printf("REAL = SHORT_MAX      '%hx'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hx'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hx'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hx'\n", -32768);
	printf("REAL = SHORT_MIN      '%hx'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hx'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hx'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhx'\n", 127);
	printf("REAL = CHAR_MAX      '%hhx'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhx'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhx'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhx'\n", -128);
	printf("REAL = CHAR_MIN      '%hhx'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhx'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhx'\n", -129);



	ft_printf("FAKE = '%0.0X'\n", -42);
	printf("REAL = '%0.0X'\n", -42);
	ft_printf("FAKE = '%0X'\n", -42);
	printf("REAL = '%0X'\n", -42);
	ft_printf("FAKE = '%#X'\n", -42);
	printf("REAL = '%#X'\n", -42);
	ft_printf("FAKE = '%10X'\n", -42);
	printf("REAL = '%10X'\n", -42);
	ft_printf("FAKE = '%10.0X'\n", 0);
	printf("REAL = '%10.0X'\n", 0);
	ft_printf("FAKE = '%0X'\n", 0);
	printf("REAL = '%0X'\n", 0);
	ft_printf("FAKE = '%.0X'\n", 0);
	printf("REAL = '%.0X'\n", 0);
	ft_printf("FAKE = '%#.2X'\n", 0);
	printf("REAL = '%#.2X'\n", 0);
	ft_printf("FAKE = '%#20X'\n", 0);
	printf("REAL = '%#20X'\n", 0);
	ft_printf("FAKE = '%#-20X'\n", 55);
	printf("REAL = '%#-20X'\n", 55);
	ft_printf("FAKE = '%0X'\n", 55);
	printf("REAL = '%0X'\n", 55);
	ft_printf("FAKE = '%.0X'\n", 55);
	printf("REAL = '%.0X'\n", 55);
	ft_printf("FAKE = '%#.2X'\n", 55);
	printf("REAL = '%#.2X'\n", 55);
	ft_printf("FAKE = '%#20X'\n", 55);
	printf("REAL = '%#20X'\n", 55);
	ft_printf("FAKE = '%#-20X'\n", 55);
	printf("REAL = '%#-20X'\n", 55);
	ft_printf("FAKE = '%#-20X'X'\n", 55);
	printf("REAL = '%#-20X'X'\n", 55);
	ft_printf("FAKE = '%0.0X'\n", 0);
	printf("REAL = '%0.0X'\n", 0);
	ft_printf("FAKE = '%#.20X'\n", 0);
	printf("REAL = '%#.20X'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llX'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llX'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llX'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llX'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llX'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llX'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llX'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llX'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lX'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lX'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lX'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lX'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lX'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lX'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lX'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lX'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%X'\n", INT_MAX);
	printf("REAL = INT_MAX      '%X'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%X'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%X'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.X'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.X'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.X'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.X'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hX'\n", 32767);
	printf("REAL = SHORT_MAX      '%hX'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hX'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hX'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hX'\n", -32768);
	printf("REAL = SHORT_MIN      '%hX'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hX'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hX'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhX'\n", 127);
	printf("REAL = CHAR_MAX      '%hhX'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhX'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhX'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhX'\n", -128);
	printf("REAL = CHAR_MIN      '%hhX'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhX'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhX'\n", -129);


	ft_printf("FAKE = '%0.0o'\n", -42);
	printf("REAL = '%0.0o'\n", -42);
	ft_printf("FAKE = '%0o'\n", -42);
	printf("REAL = '%0o'\n", -42);
	ft_printf("FAKE = '%#o'\n", -42);
	printf("REAL = '%#o'\n", -42);
	ft_printf("FAKE = '%10o'\n", -42);
	printf("REAL = '%10o'\n", -42);
	ft_printf("FAKE = '%10.0o'\n", 0);
	printf("REAL = '%10.0o'\n", 0);
	ft_printf("FAKE = '%0o'\n", 0);
	printf("REAL = '%0o'\n", 0);
	ft_printf("FAKE = '%.0o'\n", 0);
	printf("REAL = '%.0o'\n", 0);
	ft_printf("FAKE = '%#.2o'\n", 0);
	printf("REAL = '%#.2o'\n", 0);
	ft_printf("FAKE = '%#20o'\n", 0);
	printf("REAL = '%#20o'\n", 0);
	ft_printf("FAKE = '%#-20o'\n", 55);
	printf("REAL = '%#-20o'\n", 55);
	ft_printf("FAKE = '%0o'\n", 55);
	printf("REAL = '%0o'\n", 55);
	ft_printf("FAKE = '%.0o'\n", 55);
	printf("REAL = '%.0o'\n", 55);
	ft_printf("FAKE = '%#.2o'\n", 55);
	printf("REAL = '%#.2o'\n", 55);
	ft_printf("FAKE = '%#20o'\n", 55);
	printf("REAL = '%#20o'\n", 55);
	ft_printf("FAKE = '%#-20o'\n", 55);
	printf("REAL = '%#-20o'\n", 55);
	ft_printf("FAKE = '%#-20o'o'\n", 55);
	printf("REAL = '%#-20o'o'\n", 55);
	ft_printf("FAKE = '%0.0o'\n", 0);
	printf("REAL = '%0.0o'\n", 0);
	ft_printf("FAKE = '%#.20o'\n", 0);
	printf("REAL = '%#.20o'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llo'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llo'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llo'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llo'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llo'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llo'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llo'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llo'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lo'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lo'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lo'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lo'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lo'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lo'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lo'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lo'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%o'\n", INT_MAX);
	printf("REAL = INT_MAX      '%o'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%o'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%o'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.o'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.o'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.o'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.o'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%ho'\n", 32767);
	printf("REAL = SHORT_MAX      '%ho'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%ho'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%ho'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%ho'\n", -32768);
	printf("REAL = SHORT_MIN      '%ho'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%ho'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%ho'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hho'\n", 127);
	printf("REAL = CHAR_MAX      '%hho'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hho'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hho'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hho'\n", -128);
	printf("REAL = CHAR_MIN      '%hho'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hho'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hho'\n", -129);


	ft_printf("FAKE = '%0.0O'\n", -42);
	printf("REAL = '%0.0O'\n", -42);
	ft_printf("FAKE = '%0O'\n", -42);
	printf("REAL = '%0O'\n", -42);
	ft_printf("FAKE = '%#O'\n", -42);
	printf("REAL = '%#O'\n", -42);
	ft_printf("FAKE = '%10O'\n", -42);
	printf("REAL = '%10O'\n", -42);
	ft_printf("FAKE = '%10.0O'\n", 0);
	printf("REAL = '%10.0O'\n", 0);
	ft_printf("FAKE = '%0O'\n", 0);
	printf("REAL = '%0O'\n", 0);
	ft_printf("FAKE = '%.0O'\n", 0);
	printf("REAL = '%.0O'\n", 0);
	ft_printf("FAKE = '%#.2O'\n", 0);
	printf("REAL = '%#.2O'\n", 0);
	ft_printf("FAKE = '%#20O'\n", 0);
	printf("REAL = '%#20O'\n", 0);
	ft_printf("FAKE = '%#-20O'\n", 55);
	printf("REAL = '%#-20O'\n", 55);
	ft_printf("FAKE = '%0O'\n", 55);
	printf("REAL = '%0O'\n", 55);
	ft_printf("FAKE = '%.0O'\n", 55);
	printf("REAL = '%.0O'\n", 55);
	ft_printf("FAKE = '%#.2O'\n", 55);
	printf("REAL = '%#.2O'\n", 55);
	ft_printf("FAKE = '%#20O'\n", 55);
	printf("REAL = '%#20O'\n", 55);
	ft_printf("FAKE = '%#-20O'\n", 55);
	printf("REAL = '%#-20O'\n", 55);
	ft_printf("FAKE = '%#-20O'O'\n", 55);
	printf("REAL = '%#-20O'O'\n", 55);
	ft_printf("FAKE = '%0.0O'\n", 0);
	printf("REAL = '%0.0O'\n", 0);
	ft_printf("FAKE = '%#.20O'\n", 0);
	printf("REAL = '%#.20O'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llO'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llO'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llO'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llO'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llO'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llO'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llO'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llO'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lO'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lO'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lO'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lO'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lO'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lO'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lO'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lO'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%O'\n", INT_MAX);
	printf("REAL = INT_MAX      '%O'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%O'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%O'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.O'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.O'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.O'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.O'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hO'\n", 32767);
	printf("REAL = SHORT_MAX      '%hO'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hO'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hO'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hO'\n", -32768);
	printf("REAL = SHORT_MIN      '%hO'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hO'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hO'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhO'\n", 127);
	printf("REAL = CHAR_MAX      '%hhO'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhO'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhO'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhO'\n", -128);
	printf("REAL = CHAR_MIN      '%hhO'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhO'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhO'\n", -129);


	ft_printf("FAKE = '%0.0u'\n", -42);
	printf("REAL = '%0.0u'\n", -42);
	ft_printf("FAKE = '%0u'\n", -42);
	printf("REAL = '%0u'\n", -42);
	ft_printf("FAKE = '%#u'\n", -42);
	printf("REAL = '%#u'\n", -42);
	ft_printf("FAKE = '%10u'\n", -42);
	printf("REAL = '%10u'\n", -42);
	ft_printf("FAKE = '%10.0u'\n", 0);
	printf("REAL = '%10.0u'\n", 0);
	ft_printf("FAKE = '%0u'\n", 0);
	printf("REAL = '%0u'\n", 0);
	ft_printf("FAKE = '%.0u'\n", 0);
	printf("REAL = '%.0u'\n", 0);
	ft_printf("FAKE = '%#.2u'\n", 0);
	printf("REAL = '%#.2u'\n", 0);
	ft_printf("FAKE = '%#20u'\n", 0);
	printf("REAL = '%#20u'\n", 0);
	ft_printf("FAKE = '%#-20u'\n", 55);
	printf("REAL = '%#-20u'\n", 55);
	ft_printf("FAKE = '%0u'\n", 55);
	printf("REAL = '%0u'\n", 55);
	ft_printf("FAKE = '%.0u'\n", 55);
	printf("REAL = '%.0u'\n", 55);
	ft_printf("FAKE = '%#.2u'\n", 55);
	printf("REAL = '%#.2u'\n", 55);
	ft_printf("FAKE = '%#20u'\n", 55);
	printf("REAL = '%#20u'\n", 55);
	ft_printf("FAKE = '%#-20u'\n", 55);
	printf("REAL = '%#-20u'\n", 55);
	ft_printf("FAKE = '%#-20u'u'\n", 55);
	printf("REAL = '%#-20u'u'\n", 55);
	ft_printf("FAKE = '%0.0u'\n", 0);
	printf("REAL = '%0.0u'\n", 0);
	ft_printf("FAKE = '%#.20u'\n", 0);
	printf("REAL = '%#.20u'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llu'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llu'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llu'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llu'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llu'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llu'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llu'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llu'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lu'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lu'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lu'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lu'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lu'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lu'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lu'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lu'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%u'\n", INT_MAX);
	printf("REAL = INT_MAX      '%u'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%u'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%u'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.u'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.u'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.u'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.u'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hu'\n", 32767);
	printf("REAL = SHORT_MAX      '%hu'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hu'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hu'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hu'\n", -32768);
	printf("REAL = SHORT_MIN      '%hu'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hu'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hu'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhu'\n", 127);
	printf("REAL = CHAR_MAX      '%hhu'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhu'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhu'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhu'\n", -128);
	printf("REAL = CHAR_MIN      '%hhu'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhu'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhu'\n", -129);


	ft_printf("FAKE = '%0.0U'\n", -42);
	printf("REAL = '%0.0U'\n", -42);
	ft_printf("FAKE = '%0U'\n", -42);
	printf("REAL = '%0U'\n", -42);
	ft_printf("FAKE = '%#U'\n", -42);
	printf("REAL = '%#U'\n", -42);
	ft_printf("FAKE = '%10U'\n", -42);
	printf("REAL = '%10U'\n", -42);
	ft_printf("FAKE = '%10.0U'\n", 0);
	printf("REAL = '%10.0U'\n", 0);
	ft_printf("FAKE = '%0U'\n", 0);
	printf("REAL = '%0U'\n", 0);
	ft_printf("FAKE = '%.0U'\n", 0);
	printf("REAL = '%.0U'\n", 0);
	ft_printf("FAKE = '%#.2U'\n", 0);
	printf("REAL = '%#.2U'\n", 0);
	ft_printf("FAKE = '%#20U'\n", 0);
	printf("REAL = '%#20U'\n", 0);
	ft_printf("FAKE = '%#-20U'\n", 55);
	printf("REAL = '%#-20U'\n", 55);
	ft_printf("FAKE = '%0U'\n", 55);
	printf("REAL = '%0U'\n", 55);
	ft_printf("FAKE = '%.0U'\n", 55);
	printf("REAL = '%.0U'\n", 55);
	ft_printf("FAKE = '%#.2U'\n", 55);
	printf("REAL = '%#.2U'\n", 55);
	ft_printf("FAKE = '%#20U'\n", 55);
	printf("REAL = '%#20U'\n", 55);
	ft_printf("FAKE = '%#-20U'\n", 55);
	printf("REAL = '%#-20U'\n", 55);
	ft_printf("FAKE = '%#-20U'U'\n", 55);
	printf("REAL = '%#-20U'U'\n", 55);
	ft_printf("FAKE = '%0.0U'\n", 0);
	printf("REAL = '%0.0U'\n", 0);
	ft_printf("FAKE = '%#.20U'\n", 0);
	printf("REAL = '%#.20U'\n", 0);
	ft_printf("FAKE = LONG_MAX      '%llU'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%llU'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%llU'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%llU'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.llU'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.llU'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.llU'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.llU'\n", LONG_MIN - 1);
	ft_printf("FAKE = LONG_MAX      '%lU'\n", LONG_MAX);
	printf("REAL = LONG_MAX      '%lU'\n", LONG_MAX);
	ft_printf("FAKE = LONG_MAX + 1  '%lU'\n", LONG_MAX + 1);
	printf("REAL = LONG_MAX + 1  '%lU'\n", LONG_MAX + 1);
	ft_printf("FAKE = LONG_MIN      '%.lU'\n", LONG_MIN);
	printf("REAL = LONG_MIN      '%.lU'\n", LONG_MIN);
	ft_printf("FAKE = LONG_MIN - 1  '%.lU'\n", LONG_MIN - 1);
	printf("REAL = LONG_MIN - 1  '%.lU'\n", LONG_MIN - 1);
	ft_printf("FAKE = INT_MAX      '%U'\n", INT_MAX);
	printf("REAL = INT_MAX      '%U'\n", INT_MAX);
	ft_printf("FAKE = INT_MAX + 1  '%U'\n", INT_MAX + 1);
	printf("REAL = INT_MAX + 1  '%U'\n", INT_MAX + 1);
	ft_printf("FAKE = INT_MIN      '%.U'\n", INT_MIN);
	printf("REAL = INT_MIN      '%.U'\n", INT_MIN);
	ft_printf("FAKE = INT_MIN - 1  '%.U'\n", INT_MIN - 1);
	printf("REAL = INT_MIN - 1  '%.U'\n", INT_MIN - 1);
	ft_printf("FAKE = SHORT_MAX      '%hU'\n", 32767);
	printf("REAL = SHORT_MAX      '%hU'\n", 32767);
	ft_printf("FAKE = SHORT_MAX + 1  '%hU'\n", 32768);
	printf("REAL = SHORT_MAX + 1  '%hU'\n", 32768);
	ft_printf("FAKE = SHORT_MIN      '%hU'\n", -32768);
	printf("REAL = SHORT_MIN      '%hU'\n", -32768);
	ft_printf("FAKE = SHORT_MIN - 1  '%hU'\n", -32769);
	printf("REAL = SHORT_MIN - 1  '%hU'\n", -32769);
	ft_printf("FAKE = CHAR_MAX      '%hhU'\n", 127);
	printf("REAL = CHAR_MAX      '%hhU'\n", 127);
	ft_printf("FAKE = CHAR_MAX + 1  '%hhU'\n", 128);
	printf("REAL = CHAR_MAX + 1  '%hhU'\n", 128);
	ft_printf("FAKE = CHAR_MIN      '%hhU'\n", -128);
	printf("REAL = CHAR_MIN      '%hhU'\n", -128);
	ft_printf("FAKE = CHAR_MIN - 1  '%hhU'\n", -129);
	printf("REAL = CHAR_MIN - 1  '%hhU'\n", -129);


	 ft_printf("FAKE = '%0.0s'\n", "abourgay");
	 printf("REAL = '%0.0s'\n", "abourgay");
	 ft_printf("FAKE = '%0s'\n", "abourgay");
	 printf("REAL = '%0s'\n", "abourgay");
	 ft_printf("FAKE = '%#s'\n", "abourgay");
	 printf("REAL = '%#s'\n", "abourgay");
	 ft_printf("FAKE = '%10s'\n", "abourgay");
	 printf("REAL = '%10s'\n", "abourgay");
	 ft_printf("FAKE = '%10.0s'\n","abourgay");
	 printf("REAL = '%10.0s'\n","abourgay");
	 ft_printf("FAKE = '%0s'\n","abourgay");
	 printf("REAL = '%0s'\n","abourgay");
	 ft_printf("FAKE = '%.0s'\n","abourgay");
	 printf("REAL = '%.0s'\n","abourgay");
	 ft_printf("FAKE = '%#.2s'\n","abourgay");
	 printf("REAL = '%#.2s'\n","abourgay");
	 ft_printf("FAKE = '%#20s'\n","abourgay");
	 printf("REAL = '%#20s'\n","abourgay");
	 ft_printf("FAKE = '%#-20s'\n", "abourgay");
	 printf("REAL = '%#-20s'\n", "abourgay");
	 ft_printf("FAKE = '%0s'\n", "abourgay");
	 printf("REAL = '%0s'\n", "abourgay");
	 ft_printf("FAKE = '%.0s'\n", "abourgay");
	 printf("REAL = '%.0s'\n", "abourgay");
	 ft_printf("FAKE = '%#.2s'\n", "abourgay");
	 printf("REAL = '%#.2s'\n", "abourgay");
	 ft_printf("FAKE = '%#20s'\n", "abourgay");
	 printf("REAL = '%#20s'\n", "abourgay");
	 ft_printf("FAKE = '%#-20s'\n", "abourgay");
	 printf("REAL = '%#-20s'\n", "abourgay");
	 ft_printf("FAKE = '%#-20s's'\n", "abourgay");
	 printf("REAL = '%#-20s's'\n", "abourgay");
	 ft_printf("FAKE = '%0.0s'\n","abourgay");
	 printf("REAL = '%0.0s'\n","abourgay");
	 ft_printf("FAKE = '%#.20s'\n","abourgay");
	 printf("REAL = '%#.20s'\n","abourgay");*/
	return (0);
}
